config/routes.rb
Rails.application.routes.draw do

  resources :projects

  devise_for :admins, skip: :registrations

  root to: 'pages#about'

  get 'pages/resume'
  get "pages/pdf"
  get 'pages/contact'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def resume
    
  end

  def pdf
    file_name = "CharlesMilam-Resume.pdf"
    file_path ="#{Rails.root}/public/#{file_name}"
    send_file(file_path ,
    :type => 'application/pdf/docx/html/htm/doc',
    :disposition => 'attachment')  
  end   

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order(:sort)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :about, :dev_date, :repo, :url, :status, :sort, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-container">
  <!-- admin dropdown -->
  <ul class="dropdown-content" id="adminDD">
    <% if admin_signed_in? %>
      <li><%= link_to("add new project", new_project_path) %></li>
      <li><%= link_to("view all projects", projects_path) %></li>
      <li class="divider"></li>
      <li><%= link_to("sign out", destroy_admin_session_path, method: :delete) %></li>
    <% else %>
      <li><%= link_to("sign in", new_admin_session_path) %></li>
    <% end %>
  </ul>
  <nav>
    <div class="nav-wrapper">
      <!-- logo -->
      <%= link_to(root_path , class: "brand-logo") do %>
        <%= image_tag("me.jpg", class: "z-depth-1") %>
      <% end %>
      <%= link_to("charles milam", root_path , id: "logo-name") %>
      <!-- hamburger on smaller screens -->
      <%= link_to("#" , class: "button-collapse", data: {activates: "nav-med-down"}) do %>
        <i class="mdi-navigation-menu"></i>
      <% end %>

      <!-- nav links - big screen -->
      <ul class="right hide-on-med-and-down"  id="nav-large">
        <li><%= link_to("about me", root_path) %></li>
        <li><%= link_to("projects", projects_path) %></li>
        <li><%= link_to("resume", pages_resume_path) %></li>
        <li><%= link_to("contact", pages_contact_path) %></li>
        <li>
          <%= link_to("#!", class: "dropdown-button", data: {activates: "adminDD"} ) do %>
            <span>admin</span>
            <i class="mdi-navigation-arrow-drop-down right"></i>
          <% end %>
        </li>
      </ul>
      <!-- nav links - smaller screen -->
      <ul class="side-nav" id="nav-med-down">
        <li><%= link_to("about me", root_path) %></li>
        <li><%= link_to("projects", projects_path) %></li>
        <li><%= link_to("resume", pages_resume_path) %></li>
        <li><%= link_to("contact", pages_contact_path) %></li>
        <li>
          <%= link_to("#!", class: "dropdown-button", data: {activates: "adminDD"} ) do %>
            <span>admin</span>
            <i class="mdi-navigation-arrow-drop-down right"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>charles milam - portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= render "layouts/navbar" %>
  <div class="flash container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</header>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    <div class="divider"></div>
  </div>
</footer>
<script type="text/javascript">
  $(document).ready(function(){
    // init the various materialize js needed for components.
    $(".button-collapse").sideNav()
    $('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: false, // Activate on click
      alignment: 'left', // Aligns dropdown to left or right edge (works with constrain_width)
      gutter: 0, // Spacing from edge
      belowOrigin: true // Displays dropdown below the button
    })
    $('.collapsible').collapsible({
      accordion : true // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  })
</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="header">
  <h1>About me...</h1>
</div>
<div class="section">
  <p>Howdy! I'm Charles Milam. I am a native <%= link_to("Texian", "http://en.wikipedia.org/wiki/Texians", target: "_blank") %>, raised in Austin, where I currently live.</p>
  <p>I am a recent graduate of <%= link_to("MakerSquare", "http://makersquare.com", target: "_blank") %>, Cohort 10. MakerSquare is a 3 month full-time career accelerator for software developers. By teaching computer science fundamentals and modern web technologies, MakerSquare prepares students to join the workforce as full-stack web developers. We concentrated on <strong>Javascript</strong>, <strong>jQuery</strong>, <strong>Ruby</strong>, and <strong>Ruby on Rails</strong>. We had exposure to, and worked with, Javascript frameworks <strong>Mithril</strong> and <strong>React</strong>. We also made use of <strong>Sinatra</strong> and CSS frameworks <strong>Bootstrap</strong> and <strong>Foundation</strong>.
  </p> 
  <p>
    I am seeking an opportunity as a juinor level web developer. I am particularly interested in back-end development, especially with Rails, but also looking to gain experience and expand my knowledge in the front-end, and other back-end technologies. The MEAN stack and Meteor I find very interesting, and plan to explore those technologies on my own.
  </p>
  <p>
    I am a lifelong learner, and have taken recent courses on Python and MongoDB, as well as a variety of MOOCs for subjects I wanted to learn more about outside of software development. I am a subscriber to CodeSchool, and have an active profile you can see <%= link_to("here", "https://www.codeschool.com/users/Charles_Milam", target: "_blank") %>.
  </p>

</div>

app/views/pages/contact.html.erb
<div class="header">
  <h1>Contact</h1>
</div>
<div class="section">
  <div class="row">
    <div class="col s4">
      <div class="card">
        <div class="card-content">
          <span class="card-title">LinkedIn</span>
          <p>
            You can reach me at LinkedIn via the link below.
          </p>
          <div class="card-action">
            <%= link_to("linkedin", "https://www.linkedin.com/in/charlesmilam" , target: "_blank") %>
          </div>
        </div>
      </div>
    </div>
    <div class="col s4">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Twitter</span>
          <p>
            You can reach me via Twitter via the link below.
          </p>
          <div class="card-action">
            <%= link_to("twitter", "https://twitter.com/chrlsmlm" , target: "_blank") %>
          </div>
        </div>
      </div>
    </div>
    <div class="col s4">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Email</span>
          <p>
            You can reach me @ Gmail, and my address is my first and last name seperated by a dot.
          </p>
          <div class="card-action"></div>
        </div>
      </div>
    </div>
  </div>   
</div>

app/views/pages/resume.html.erb
 <h1>R&eacutesum&eacute</h1>
 <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header active"><i class="mdi-action-subject"></i>Summary of Qualifications</div>
      <div class="collapsible-body">
        <p>
          Fundamental knowledge of web application technologies, to include <strong>Ruby/RoR</strong>, <strong>HTML/CSS</strong>, <strong>Javascript/jQuery</strong>. Strong multi-tasking skills and attention to detail. Experience working on collaborative projects. 8+ years of programming experience (Visual Basic for Applications). Extensive experience in logistics/material handling, particularly as it pertains to high-tech manufacturing. Well versed in ISO 9000 documentation, LEAN manufacturing principles, JIT material management, continuous quality improvement principles, and all aspects of electronic and manual inventory management and control. 
        </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-action-subject"></i>Experience</div>
      <div class="collapsible-body">
        <p>
          <strong>Software Developer</strong>:<br>
          <strong>MakerSquare - Tatalog - Capstone Individual Project</strong> - (Feb 2015) <br>
          <%= link_to("Github repository", "https://github.com/CharlesMilam/tatalog", target: "_blank") %> <br>
          Tatalog is a web application to aid an individual in organizing photos of their tattoos, with relevant information regarding each tattoo, as well as a providing for the categorization of ideas for future tattoos. Performed full-stack web development, utilizing Ruby on Rails. Employed  Foundation 5 CSS framework. Deployed application on Heroku. 
          <br><br>
          <strong>MakerSquare - Cliqr - Capstone Group Project</strong>  - (Jan 2015 - Feb 2015) <br>
          <%= link_to("Github repository", "https://github.com/bashmb/cliqr", target: "_blank") %> <br>
          The purpose of this project is to increase lecture interactivity and improve learning outcomes by breaking down instructor/student and student/student barriers to communication. Primary responsibilities as team member of the Cliqr project was the writing of all unit, functional and integration tests, Github documentation, in the form of a wiki, primary maintainer of project backlog and issues. Also wrote and implemented all database migrations pertaining to project. Performed a variety of project debugging tasks, on both the front-end and back-end.
          <br><br>
          <strong>User Systems Analyst:</strong><br>
          <strong>Applied Materials</strong> - (1994 - 2004)<br>
          Utilized MS Access to create a variety of rapidly developed and deployed database applications to support the materials and logistics organizations of the Physical Vapor Deposition division. Made extensive use of Visual Basic for Applications to provide functionality and features not available in a typical “out of the box” install of Access. <br>
          <span class="amat-hi"><strong>Highlights</strong>:</span><br>
          <span class="amat-hi">
            <strong>Production Status database application</strong>: Tracked the status of all systems in production on the manufacturing floor, to include key milestones and part shortages. Replaced a variety individual spreadsheets each project manager maintained, with a central repository for all production status information and common reporting structure.
          </span>
          <br>
          <span class="amat-hi">
            <strong>Virtual warehouse</strong>: Allowed for accurate storage, retrieval and tracking of manufacturing parts that were held in temporary storage locations that were not able to utilize the corporate ERP system due to constraints of that system. Utilized barcodes and scanners to increase accuracy and speed of data entry. This application greatly reduced misplacement of manufacturing parts located in temporary storage locations, as well as increased their retrieval time and delivery. Also provided visibility of these parts to other members of the organization.
          </span>
          <br>
          <span class="amat-hi">
            <strong>Obsolete and excess inventory</strong>: Provided for the reconciliation and disposition of obsolete and excess inventory against the corporate ERP system. Eliminated a very manual and paper-based process with one that automated many of the steps of the process, and greatly reduced data entry errors, as well as increasing the overall speed of the process. 
          </span>
          <br><br>
          <strong>Medic I</strong>:<br>
          <strong>Austin/Travis County EMS</strong> - (2012 - 2014) <br>
          Front-line medic on ambulance responding to 911 dispatched medical emergencies.<br> 
          Utilized established protocols to provide medical care in a high stress and time sensitive environment.<br>
          Worked in a collaborative environment that included a variety of first responder organizations to provide a high level of customer satisfaction.
          <br><br>
          <strong>Temporary Retirement/Dad</strong> - (2004 - 2012) <br>
          Took advantage of opportunity to devote time to the raising of my two daughters.<br>
        </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-action-subject"></i>Education</div>
      <div class="collapsible-body">
        <p>
          <strong>MakerSquare</strong>, Austin, Texas - (Nov 2014 - Feb 2015)
          MakerSquare is a 3 month full-time career accelerator for software developers. By teaching computer science fundamentals and modern web technologies, MakerSquare prepares students to join the workforce as full-stack web developers.                                                                             
          <br><br>
          <strong>Austin Community College</strong>, Austin, Texas - (Spring 2012)      
          Associates of Science - Emergency Medical Services Professions        
          <br><br>
          <strong>Austin Community College</strong>, Austin, Texas - (Fall 1996)
          Associates of Arts - Communications
          <br><br>
        </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-action-subject"></i>Side Projects</div>
      <div class="collapsible-body">
        <p>
          <strong>Lunar Lander</strong> - proof of concept project using python and the Kivy library for python. Kivy allows for the creation of standalone Android apps.
          <%= link_to("Github repository", "https://github.com/HurtCircus/lander" , target: "_blank") %> 
          <br><br>

          <strong>ATX-MDG</strong> - A python based (using Kivy library) project to create an Android app to give paramedics easy and quick access to a drug list used in their clinical operating guidelines. Includes information such as dosages, indications for use, adverse reactions, &c.
          <%= link_to("Github repository", "https://github.com/HurtCircus/ATX-MDG" , target: "_blank") %> 
        </p>
      </div>
    </li>
    <li>
      <div class="collapsible-header"><i class="mdi-action-subject"></i>Activities</div>
      <div class="collapsible-body">
        <p>
          Member of board of directors of Central Texas Motorcycle Charities, a 501c3 non-profit organization, for 12+ years.<br>
          Registration czar and lead for the Harvest Classic charity motorcycle rally supporting the Candlelighters Childhood Cancer Foundation for 12+ years.<br>
          Volunteered 15+ years with Meals on Wheels in the Manor, TX area.<br>
          Served as parent representative on the board of Faith Lutheran Child Development Center 2000-2002.  
        </p>
      </div>
    </li>
    <li>
    <div class="collapsible-header"><i class="mdi-file-cloud-download"></i>Download Resume</div>
      <div class="collapsible-body">
        <p>
          <%= link_to("Download Charles Milam resume", pages_pdf_path, target: "_self") %>
        </p>
      </div>
    </li>
  </ul>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :dev_date %><br>
    <%= f.text_field :dev_date %>
  </div>
  <div class="field">
    <%= f.label :repo %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.text_field :sort %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.button "add project", class: "btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Projects</h1>

<div class="row">
  <% @projects.each do |project| %>
    <div class="col s12 l6">
      <div class="card medium">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag(project.image, class: "activator") %>
        </div>
        <div class="card-content">
          <span class="card-title activator white-text"><%= project.name %><i class="mdi-navigation-more-vert right"></i></span>
        </div>
         <div class="card-reveal">
          <span class="card-title black-text lighten-2"><%= project.name %><i class="mdi-navigation-close right"></i></span>
          <p><%= simple_format(project.about) %></p>
        </div>
        <div class="card-action">
          <%= link_to("github repository", project.repo, target: "_blank") %><br>
          <%= link_to("project website", project.url , target: "_blank") %><br>
          <% if admin_signed_in? %>
            <%= link_to("Edit this project", edit_project_path(project)) %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

 <!-- only show to admins -->
 <% if admin_signed_in? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@project.image, width: 600) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>About:</strong>
  <%= simple_format(@project.about) %>
</p>

<p>
  <strong>Dev date:</strong>
  <%= @project.dev_date %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @project.repo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Sort</strong>
  <%= @project.sort %>
</p>

<!-- only allow admins to see edit link -->
<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>